// --- Constantes ---
// Remoção de "Magic Numbers".
const API_BASE_URL = 'https://api.potterdb.com/v1';
const MAX_RANDOM_PAGES = 8;
const PAGE_SIZE = 100;
const CARDS_IN_PACK = 4;
const CARDS_IN_CPU_DECK = 2;
const NUMBER_OF_SPELLS_RETURNED = 20;

const DEFAULT_POWER = 50;
const GRYFFINDOR_POWER = 90;
const SLYTHERIN_POWER = 85;
const HUFFLEPUFF_POWER = 75;
const RAVENCLAW_POWER = 80;

const DEFAULT_MAGIC = 50;
const HUMAN_MAGIC = 70;
const HALF_GIANT_MAGIC = 88;
const GIANT_MAGIC = 95;
const HOUSE_ELF_MAGIC = 82;
const GHOST_MAGIC = 60;
const WEREWOLF_MAGIC = 91;
const VAMPIRE_MAGIC = 87;
const CENTAUR_MAGIC = 78;

const DEFAULT_DEFENSE = 50;
const PURE_BLOOD_DEFENSE = 90;
const HALF_BLOOD_DEFENSE = 75;
const MUGGLE_BORN_DEFENSE = 70;
const MUGGLE_DEFENSE = 40;
const SQUIB_DEFENSE = 35;

const HP_BASE = 80;
const HP_VARIANCE = 20;

const DEFAULT_DAMAGE = 30;
const CHARM_DAMAGE = 45;
const CURSE_DAMAGE = 90;
const HEX_DAMAGE = 65;
const JINX_DAMAGE = 55;
const SPELL_CATEGORY_DAMAGE = 50;
const TRANSFIGURATION_DAMAGE = 40;
const COUNTER_SPELL_DAMAGE = 35;
const HEALING_SPELL_DAMAGE = -40;

// Exportando as constantes para que o arquivo principal possa importá-las
module.exports = {
  API_BASE_URL,
  MAX_RANDOM_PAGES,
  PAGE_SIZE,
  CARDS_IN_PACK,
  CARDS_IN_CPU_DECK,
  NUMBER_OF_SPELLS_RETURNED,
  DEFAULT_POWER,
  GRYFFINDOR_POWER,
  SLYTHERIN_POWER,
  HUFFLEPUFF_POWER,
  RAVENCLAW_POWER,
  DEFAULT_MAGIC,
  HUMAN_MAGIC,
  HALF_GIANT_MAGIC,
  GIANT_MAGIC,
  HOUSE_ELF_MAGIC,
  GHOST_MAGIC,
  WEREWOLF_MAGIC,
  VAMPIRE_MAGIC,
  CENTAUR_MAGIC,
  DEFAULT_DEFENSE,
  PURE_BLOOD_DEFENSE,
  HALF_BLOOD_DEFENSE,
  MUGGLE_BORN_DEFENSE,
  MUGGLE_DEFENSE,
  SQUIB_DEFENSE,
  HP_BASE,
  HP_VARIANCE,
  DEFAULT_DAMAGE,
  CHARM_DAMAGE,
  CURSE_DAMAGE,
  HEX_DAMAGE,
  JINX_DAMAGE,
  SPELL_CATEGORY_DAMAGE,
  TRANSFIGURATION_DAMAGE,
  COUNTER_SPELL_DAMAGE,
  HEALING_SPELL_DAMAGE,
};
